using App.Client;
using App.Shared;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App.Client.App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

// Named HttpClient "App" matches [ApiRoute(..., HttpClientName = "App")] in IModsApi, and is
// resolved by the RouteGen-generated HttpModsApi via IHttpClientFactory.
builder.Services.AddHttpClient("App", client =>
{
    client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress);
});

// Generated by RouteGen (see obj/**/generated/RouteGen.Generators/.../Client_IModsApi.g.cs after
// build) — no hand-written HttpClient calls or URL strings anywhere in the UI code below.
builder.Services.AddScoped<IModsApi, HttpModsApi>();

await builder.Build().RunAsync();
