using System.Linq;
using System.Text;

namespace RouteGen.Generators;

internal static class ClientImplementationEmitter
{
    public static string Emit(ApiInterfaceModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// GENERATED by RouteGen from " + model.InterfaceName + " — do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        string indent = hasNamespace ? "    " : "";
        string className = "Http" + model.ShortName + "Api";
        string fqInterface = string.IsNullOrEmpty(model.Namespace)
            ? "global::" + model.InterfaceName
            : "global::" + model.Namespace + "." + model.InterfaceName;

        sb.Append(indent).Append("public sealed class ").Append(className)
          .Append("(global::System.Net.Http.IHttpClientFactory factory) : ").AppendLine(fqInterface);
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    private readonly HttpClient _http = factory.CreateClient(\"")
          .Append(EscapeString(model.HttpClientName)).AppendLine("\");");
        sb.AppendLine();

        foreach (var method in model.Methods)
        {
            EmitClientMethod(sb, indent + "    ", model, method);
        }

        sb.Append(indent).AppendLine("}");
        if (hasNamespace) sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitClientMethod(StringBuilder sb, string indent, ApiInterfaceModel model, ApiMethodModel method)
    {
        string returnType = method.ResponseTypeFullName is null
            ? "global::System.Threading.Tasks.Task"
            : $"global::System.Threading.Tasks.Task<{method.ResponseTypeFullName}>";

        var paramList = string.Join(", ", method.Parameters.Select(FormatParameter));
        sb.Append(indent).Append("public async ").Append(returnType).Append(' ').Append(method.Name)
          .Append('(').Append(paramList).AppendLine(")");
        sb.Append(indent).AppendLine("{");

        string bodyIndent = indent + "    ";

        string template = RouteTemplateParser.Combine(model.BaseRoute, method.RouteSuffix);
        var tokens = RouteTemplateParser.ExtractTokens(template);

        sb.Append(bodyIndent).Append("var __url = new StringBuilder(\"");
        sb.Append(BuildInterpolatedTemplateLiteral(template, method));
        sb.AppendLine("\");");

        var queryParams = method.Parameters.Where(p => p.Kind == ParameterKind.Query).ToList();
        if (queryParams.Count > 0)
        {
            sb.Append(bodyIndent).AppendLine("var __query = new System.Collections.Generic.List<string>();");
            foreach (var q in queryParams)
            {
                if (q.TypeFullName.EndsWith("?"))
                {
                    bool isNullableString = q.TypeFullName == "string?";
                    string valueExpr = isNullableString ? q.Name : q.Name + ".Value.ToString()";
                    sb.Append(bodyIndent).Append("if (").Append(q.Name).AppendLine(" is not null)");
                    sb.Append(bodyIndent).Append("    __query.Add($\"")
                      .Append(q.Name).Append("={Uri.EscapeDataString(").Append(valueExpr).AppendLine(" ?? string.Empty)}\");");
                }
                else
                {
                    sb.Append(bodyIndent).Append("__query.Add($\"").Append(q.Name)
                      .Append("={Uri.EscapeDataString(").Append(q.Name).AppendLine(".ToString() ?? string.Empty)}\");");
                }
            }
            sb.Append(bodyIndent).AppendLine("if (__query.Count > 0) __url.Append('?').Append(string.Join(\"&\", __query));");
        }

        var ctParam = method.Parameters.FirstOrDefault(p => p.Kind == ParameterKind.CancellationToken);
        string ctArg = ctParam is not null ? ctParam.Name : "CancellationToken.None";

        var bodyParam = method.Parameters.FirstOrDefault(p => p.Kind == ParameterKind.Body);

        string httpCall = method.Verb switch
        {
            "GET" => "_http.GetAsync(__url.ToString(), " + ctArg + ")",
            "DELETE" => "_http.DeleteAsync(__url.ToString(), " + ctArg + ")",
            "POST" => bodyParam is not null
                ? $"_http.PostAsJsonAsync(__url.ToString(), {bodyParam.Name}, {ctArg})"
                : $"_http.PostAsync(__url.ToString(), null, {ctArg})",
            "PUT" => bodyParam is not null
                ? $"_http.PutAsJsonAsync(__url.ToString(), {bodyParam.Name}, {ctArg})"
                : $"_http.PutAsync(__url.ToString(), null, {ctArg})",
            "PATCH" => bodyParam is not null
                ? $"_http.PatchAsJsonAsync(__url.ToString(), {bodyParam.Name}, {ctArg})"
                : $"_http.PatchAsync(__url.ToString(), null, {ctArg})",
            _ => "_http.GetAsync(__url.ToString(), " + ctArg + ")"
        };

        sb.Append(bodyIndent).Append("var __response = await ").Append(httpCall).AppendLine(";");
        sb.Append(bodyIndent).AppendLine("if (!__response.IsSuccessStatusCode)");
        sb.Append(bodyIndent).AppendLine("{");
        sb.Append(bodyIndent).Append("    var __errorBody = await __response.Content.ReadAsStringAsync(").Append(ctParam is not null ? ctArg : "").AppendLine(");");
        sb.Append(bodyIndent).AppendLine("    throw new global::RouteGen.ApiException(__response.StatusCode, __errorBody);");
        sb.Append(bodyIndent).AppendLine("}");

        if (method.ResponseTypeFullName is null)
        {
            // Task, no response body expected.
        }
        else if (method.IsStreamResponse)
        {
            sb.Append(bodyIndent).Append("return await __response.Content.ReadAsStreamAsync(").Append(ctParam is not null ? ctArg : "").AppendLine(");");
        }
        else
        {
            sb.Append(bodyIndent).Append("return (await __response.Content.ReadFromJsonAsync<")
              .Append(method.ResponseTypeFullName).Append(">(cancellationToken: ").Append(ctArg).AppendLine("))!;");
        }

        sb.Append(indent).AppendLine("}");
        sb.AppendLine();
    }

    private static string BuildInterpolatedTemplateLiteral(string template, ApiMethodModel method)
    {
        var sb = new StringBuilder();
        int i = 0;
        while (i < template.Length)
        {
            if (template[i] == '{')
            {
                int close = template.IndexOf('}', i + 1);
                if (close < 0) { sb.Append(template[i]); i++; continue; }
                string inner = template.Substring(i + 1, close - i - 1);
                i = close + 1;
                string name = inner;
                int colon = name.IndexOf(':');
                if (colon >= 0) name = name.Substring(0, colon);
                name = name.TrimEnd('?');
                int eq = name.IndexOf('=');
                if (eq >= 0) name = name.Substring(0, eq);

                var param = method.Parameters.FirstOrDefault(p =>
                    p.MatchesRouteToken &&
                    string.Equals(p.RouteTokenNameOverride ?? p.Name, name, System.StringComparison.OrdinalIgnoreCase));

                if (param is not null)
                {
                    sb.Append("\" + Uri.EscapeDataString(").Append(param.Name).Append(".ToString() ?? string.Empty) + \"");
                }
                else
                {
                    sb.Append('{').Append(inner).Append('}');
                }
            }
            else if (template[i] == '"' || template[i] == '\\')
            {
                sb.Append('\\').Append(template[i]);
                i++;
            }
            else
            {
                sb.Append(template[i]);
                i++;
            }
        }
        return sb.ToString();
    }

    private static string FormatParameter(ApiParameterModel p)
    {
        if (p.Kind == ParameterKind.CancellationToken)
            return "CancellationToken " + p.Name + " = default";

        string result = p.TypeFullName + " " + p.Name;
        if (p.HasDefaultValue)
            result += " = " + p.DefaultValueLiteral;
        return result;
    }

    private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
