using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;

namespace RouteGen.Generators;

/// <summary>
/// Scans every <c>.razor</c> file passed to the compilation as an <c>AdditionalText</c> for
/// <c>@page "..."</c> directives (including route-parameter syntax such as <c>{id:int}</c> and
/// optional <c>{id:int?}</c>), and emits a strongly-typed static <c>Paths</c> class with one
/// member per distinct page route, so Blazor page routes require zero hand-written duplication.
///
/// Consuming projects must add their .razor files as AdditionalFiles, e.g.:
/// <code>&lt;ItemGroup&gt;&lt;AdditionalFiles Include="**/*.razor" /&gt;&lt;/ItemGroup&gt;</code>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class PageRouteGenerator : IIncrementalGenerator
{
    private static readonly Regex PageDirectiveRegex = new(
        "^\\s*@page\\s+\"([^\"]+)\"", RegexOptions.Compiled | RegexOptions.Multiline);

    /// <summary>Opt-in override, e.g. <c>@attribute [GeneratedPathName("ModDetail")]</c>.</summary>
    private static readonly Regex GeneratedPathNameRegex = new(
        "@attribute\\s+\\[\\s*GeneratedPathName\\s*\\(\\s*\"([^\"]+)\"\\s*\\)\\s*\\]", RegexOptions.Compiled);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var razorFiles = context.AdditionalTextsProvider
            .Where(static text => text.Path.EndsWith(".razor", System.StringComparison.OrdinalIgnoreCase));

        var parsedPages = razorFiles
            .Select(static (text, ct) => ParsePage(text, ct))
            .Where(static page => page is not null);

        var rootNamespace = context.AnalyzerConfigOptionsProvider.Select(static (options, _) =>
            options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns) && !string.IsNullOrEmpty(ns)
                ? ns!
                : "Generated");

        var combined = parsedPages.Collect().Combine(rootNamespace);

        context.RegisterSourceOutput(combined, static (spc, pair) =>
        {
            var (pages, ns) = pair;
            var validPages = pages.Where(p => p is not null).Select(p => p!).ToList();
            if (validPages.Count == 0) return;

            var used = new Dictionary<string, PageRouteInfo>();
            var members = new List<PageRouteInfo>();

            foreach (var page in validPages.OrderBy(p => p.MemberName, System.StringComparer.Ordinal))
            {
                if (used.ContainsKey(page.MemberName))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(RouteGenDiagnostics.AmbiguousPageRouteMember, Location.None, page.MemberName));
                    continue;
                }
                used[page.MemberName] = page;
                members.Add(page);
            }

            spc.AddSource("Paths.g.cs", EmitPathsClass(ns, members));
        });
    }

    private static PageRouteInfo? ParsePage(AdditionalText text, System.Threading.CancellationToken ct)
    {
        var sourceText = text.GetText(ct);
        if (sourceText is null) return null;
        string content = sourceText.ToString();

        var match = PageDirectiveRegex.Match(content);
        if (!match.Success) return null;
        string route = match.Groups[1].Value;

        string? overrideName = null;
        var nameMatch = GeneratedPathNameRegex.Match(content);
        if (nameMatch.Success) overrideName = nameMatch.Groups[1].Value;

        string fileName = System.IO.Path.GetFileNameWithoutExtension(text.Path);
        string memberName = overrideName ?? SanitizeIdentifier(fileName);

        var tokens = RouteTemplateParser.ExtractTokens(route);
        return new PageRouteInfo(memberName, route, tokens);
    }

    private static string SanitizeIdentifier(string name)
    {
        var sb = new StringBuilder();
        foreach (char c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_') sb.Append(c);
        }
        if (sb.Length == 0) return "Page";
        if (char.IsDigit(sb[0])) sb.Insert(0, '_');
        return sb.ToString();
    }

    private static string EmitPathsClass(string rootNamespace, List<PageRouteInfo> pages)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// GENERATED by RouteGen from @page directives — do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.Append("namespace ").Append(rootNamespace).AppendLine(".Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public static class Paths");
        sb.AppendLine("    {");

        foreach (var page in pages)
        {
            if (page.Tokens.Count == 0)
            {
                sb.Append("        public const string ").Append(page.MemberName)
                  .Append(" = \"").Append(EscapeString(page.Route)).AppendLine("\";");
            }
            else
            {
                var parameters = page.Tokens
                    .Select(t => (Name: SanitizeIdentifier(LowerFirst(t.Name)), Type: MapConstraintToType(t.Constraint), Token: t))
                    .ToList();

                string paramList = string.Join(", ", parameters.Select(p => $"{p.Type} {p.Name}"));
                sb.Append("        public static string ").Append(page.MemberName).Append('(').Append(paramList).AppendLine(")");
                sb.Append("            => $\"").Append(BuildInterpolated(page.Route, parameters)).AppendLine("\";");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string BuildInterpolated(string route, List<(string Name, string Type, RouteToken Token)> parameters)
    {
        var sb = new StringBuilder();
        int i = 0;
        while (i < route.Length)
        {
            if (route[i] == '{')
            {
                int close = route.IndexOf('}', i + 1);
                if (close < 0) { sb.Append(route[i]); i++; continue; }
                string inner = route.Substring(i + 1, close - i - 1);
                i = close + 1;
                string name = inner;
                int colon = name.IndexOf(':');
                if (colon >= 0) name = name.Substring(0, colon);
                name = name.TrimEnd('?');

                var match = parameters.FirstOrDefault(p => string.Equals(p.Token.Name, name, System.StringComparison.OrdinalIgnoreCase));
                if (match.Name is not null)
                {
                    if (match.Type == "string")
                        sb.Append("{Uri.EscapeDataString(").Append(match.Name).Append(")}");
                    else
                        sb.Append('{').Append(match.Name).Append('}');
                }
            }
            else
            {
                sb.Append(route[i]);
                i++;
            }
        }
        return sb.ToString();
    }

    private static string MapConstraintToType(string? constraint) => constraint switch
    {
        "int" => "int",
        "long" => "long",
        "bool" => "bool",
        "double" => "double",
        "decimal" => "decimal",
        "guid" => "Guid",
        "datetime" => "DateTime",
        _ => "string"
    };

    private static string LowerFirst(string s) => s.Length == 0 ? s : char.ToLowerInvariant(s[0]) + s.Substring(1);

    private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed class PageRouteInfo
    {
        public string MemberName { get; }
        public string Route { get; }
        public IReadOnlyList<RouteToken> Tokens { get; }

        public PageRouteInfo(string memberName, string route, IReadOnlyList<RouteToken> tokens)
        {
            MemberName = memberName;
            Route = route;
            Tokens = tokens;
        }
    }
}
