using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using RouteGen.Generators.Diagnostics;
using RouteGen.Generators.Parsing;

namespace RouteGen.Generators;

/// <summary>
/// Scans every <c>.razor</c> file exposed to the compilation as an <c>AdditionalText</c> (see
/// <c>build/RouteGen.targets</c>, which adds <c>**/*.razor</c> as AdditionalFiles) for
/// <c>@page "..."</c> directives, and emits a single static <c>Paths</c> class with one member
/// per route — a constant for parameterless routes, a method for parameterized ones.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class PathsGenerator : IIncrementalGenerator
{
    private static readonly Regex PageDirectiveRegex = new("@page\\s+\"([^\"]*)\"", RegexOptions.Compiled);
    private static readonly Regex AttributeOverrideRegex = new("@attribute\\s+\\[\\s*GeneratedPathName\\s*\\(\\s*\"([^\"]*)\"\\s*\\)\\s*\\]", RegexOptions.Compiled);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var razorFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, ct) =>
            {
                var text = file.GetText(ct);
                return text is null ? null : ParseRazorFile(file.Path, text.ToString());
            })
            .Where(static parsed => parsed is not null)
            .Select(static (parsed, _) => parsed!.Value)
            .Collect();

        context.RegisterSourceOutput(razorFiles, static (spc, pages) =>
        {
            if (pages.IsDefaultOrEmpty)
            {
                return;
            }

            var (source, diagnostics) = GeneratePathsClass(pages);
            foreach (var d in diagnostics)
            {
                spc.ReportDiagnostic(d);
            }

            spc.AddSource("Paths.g.cs", source);
        });
    }

    private static RazorPage? ParseRazorFile(string path, string content)
    {
        var match = PageDirectiveRegex.Match(content);
        if (!match.Success)
        {
            return null;
        }

        var route = match.Groups[1].Value;
        var overrideMatch = AttributeOverrideRegex.Match(content);
        var nameOverride = overrideMatch.Success ? overrideMatch.Groups[1].Value : null;
        return new RazorPage(path, route, nameOverride);
    }

    private static (string Source, List<Diagnostic> Diagnostics) GeneratePathsClass(ImmutableArray<RazorPage> pages)
    {
        var diagnostics = new List<Diagnostic>();
        var usedNames = new Dictionary<string, RazorPage>();
        var members = new List<(string Name, RazorPage Page)>();

        foreach (var page in pages.OrderBy(p => p.Route, StringComparer.Ordinal))
        {
            var name = page.NameOverride ?? DeriveMemberName(page.Path);
            if (usedNames.TryGetValue(name, out var existing))
            {
                diagnostics.Add(Diagnostic.Create(
                    DiagnosticDescriptors.AmbiguousRazorPageName,
                    Location.None,
                    page.Route, existing.Path, page.Path, name));
                continue; // skip the duplicate; first one wins, matching a stable/deterministic order
            }

            usedNames[name] = page;
            members.Add((name, page));
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by RouteGen from @page directives — do not edit. />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("public static class Paths");
        sb.AppendLine("{");

        foreach (var (name, page) in members)
        {
            var tokens = RouteTemplate.ParseTokens(page.Route);
            if (tokens.Count == 0)
            {
                sb.Append("    public const string ").Append(name).Append(" = \"").Append(page.Route).AppendLine("\";");
            }
            else
            {
                var parameters = string.Join(", ", tokens.Select(t => $"{MapConstraintToType(t.Constraint)} {t.Name}"));
                sb.Append("    public static string ").Append(name).Append('(').Append(parameters).AppendLine(")");
                sb.Append("        => $\"").Append(BuildInterpolated(page.Route, tokens)).AppendLine("\";");
            }
        }

        sb.AppendLine("}");
        return (sb.ToString(), diagnostics);
    }

    private static string BuildInterpolated(string route, IReadOnlyList<RouteToken> tokens)
    {
        var sb = new StringBuilder();
        var i = 0;
        while (i < route.Length)
        {
            if (route[i] == '{')
            {
                var close = route.IndexOf('}', i + 1);
                var inner = route.Substring(i + 1, close - i - 1);
                var name = inner.Split(':')[0].TrimEnd('?');
                var isString = tokens.First(t => t.Name == name).Constraint is null;
                sb.Append('{').Append(isString ? $"Uri.EscapeDataString({name})" : name).Append('}');
                i = close + 1;
            }
            else
            {
                sb.Append(route[i]);
                i++;
            }
        }

        return sb.ToString();
    }

    private static string MapConstraintToType(string? constraint) => constraint switch
    {
        "int" => "int",
        "long" => "long",
        "bool" => "bool",
        "guid" => "Guid",
        "datetime" => "DateTime",
        "decimal" => "decimal",
        "double" => "double",
        "float" => "float",
        _ => "string",
    };

    /// <summary>
    /// Default naming heuristic: use the .razor file's own name (without extension), converted
    /// to PascalCase word-by-word. E.g. "mod-detail.razor" -&gt; "ModDetail", "Index.razor" in a
    /// "Profile" folder -&gt; "Index" (folder is NOT included by default — use
    /// [GeneratedPathName("...")] when that's ambiguous, per RG0101).
    /// </summary>
    private static string DeriveMemberName(string path)
    {
        var fileName = Path.GetFileNameWithoutExtension(path);
        var parts = fileName.Split(new[] { '-', '_', '.' }, StringSplitOptions.RemoveEmptyEntries);
        var sb = new StringBuilder();
        foreach (var part in parts)
        {
            if (part.Length == 0)
            {
                continue;
            }

            sb.Append(char.ToUpperInvariant(part[0]));
            if (part.Length > 1)
            {
                sb.Append(part.Substring(1));
            }
        }

        var name = sb.ToString();
        return name.Length == 0 ? "Page" : name;
    }

    private readonly record struct RazorPage(string Path, string Route, string? NameOverride);
}
