using System.Linq;
using System.Text;
using RouteGen.Generators.Model;
using RouteGen.Generators.Parsing;

namespace RouteGen.Generators.Emission;

internal static class ClientEmitter
{
    public static string Generate(ApiInterfaceModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by RouteGen — do not edit. Regenerated on every build. />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.Http;");
        sb.AppendLine("using RouteGen.Abstractions;");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        var indent = hasNamespace ? "    " : "";
        var className = "Http" + (model.InterfaceName.StartsWith("I") && model.InterfaceName.Length > 1 && char.IsUpper(model.InterfaceName[1])
            ? model.InterfaceName.Substring(1)
            : model.InterfaceName);
        var clientName = model.HttpClientName ?? string.Empty;

        sb.Append(indent).Append("public sealed class ").Append(className)
          .Append("(IHttpClientFactory httpClientFactory) : ").Append(model.InterfaceName).AppendLine();
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    private readonly IHttpClientFactory _httpClientFactory = httpClientFactory;");
        sb.Append(indent).Append("    private readonly HttpClient _http = httpClientFactory.CreateClient(\"").Append(clientName).AppendLine("\");");
        sb.AppendLine();

        foreach (var method in model.Methods)
        {
            EmitMethod(sb, indent + "    ", model, method);
        }

        sb.Append(indent).AppendLine("}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void EmitMethod(StringBuilder sb, string indent, ApiInterfaceModel model, ApiMethodModel method)
    {
        var returnType = method.ReturnKind switch
        {
            ApiMethodReturnKind.TaskVoid => "Task",
            ApiMethodReturnKind.TaskOfStream => $"Task<{method.UnwrappedReturnTypeDisplayString}>",
            _ => $"Task<{method.UnwrappedReturnTypeDisplayString}>",
        };

        var clientNameForMethod = method.HttpClientNameOverride;
        var usesOwnClient = clientNameForMethod is not null;

        sb.Append(indent).Append("public async ").Append(returnType).Append(' ').Append(method.Name).Append('(');
        sb.Append(string.Join(", ", method.Parameters.Select(FormatParameter)));
        sb.AppendLine(")");
        sb.Append(indent).AppendLine("{");

        if (usesOwnClient)
        {
            sb.Append(indent).Append("    var http = _httpClientFactory.CreateClient(\"").Append(clientNameForMethod).AppendLine("\");");
        }

        var httpVar = usesOwnClient ? "http" : "_http";

        // Build the route path by substituting {token} occurrences.
        var routeExpr = BuildRouteInterpolatedString(method);
        sb.Append(indent).Append("    var url = ").Append(routeExpr).AppendLine(";");

        var queryParams = method.Parameters.Where(p => p.Kind == ParameterKind.Query).ToArray();
        if (queryParams.Length > 0)
        {
            sb.Append(indent).AppendLine("    var query = new System.Collections.Generic.List<string>();");
            foreach (var q in queryParams)
            {
                var isReferenceOrNullable = q.IsNullable || q.TypeDisplayString.EndsWith("?");
                var accessor = q.TypeDisplayString.TrimEnd('?') == "string"
                    ? $"Uri.EscapeDataString({q.Name})"
                    : $"Uri.EscapeDataString({q.Name}.ToString()!)";
                if (isReferenceOrNullable)
                {
                    sb.Append(indent).Append("    if (").Append(q.Name).AppendLine(" is not null)");
                    sb.Append(indent).Append("        query.Add(\"").Append(q.Name).Append("=\" + ").Append(accessor).AppendLine(");");
                }
                else
                {
                    sb.Append(indent).Append("    query.Add(\"").Append(q.Name).Append("=\" + ").Append(accessor).AppendLine(");");
                }
            }

            sb.Append(indent).AppendLine("    if (query.Count > 0) url += \"?\" + string.Join(\"&\", query);");
        }

        var bodyParam = method.Parameters.FirstOrDefault(p => p.Kind == ParameterKind.Body);
        var ctParam = method.Parameters.FirstOrDefault(p => p.Kind == ParameterKind.CancellationToken);
        var ctArg = ctParam is not null ? $", {ctParam.Name}" : "";

        var httpMethodCall = method.HttpVerb switch
        {
            "GET" => $"{httpVar}.GetAsync(url{ctArg})",
            "DELETE" => $"{httpVar}.DeleteAsync(url{ctArg})",
            "POST" when bodyParam is not null => $"{httpVar}.PostAsJsonAsync(url, {bodyParam.Name}{ctArg})",
            "POST" => $"{httpVar}.PostAsync(url, content: null{ctArg})",
            "PUT" when bodyParam is not null => $"{httpVar}.PutAsJsonAsync(url, {bodyParam.Name}{ctArg})",
            "PUT" => $"{httpVar}.PutAsync(url, content: null{ctArg})",
            "PATCH" when bodyParam is not null => $"{httpVar}.PatchAsJsonAsync(url, {bodyParam.Name}{ctArg})",
            "PATCH" => $"{httpVar}.PatchAsync(url, content: null{ctArg})",
            _ => $"{httpVar}.GetAsync(url{ctArg})",
        };

        sb.Append(indent).Append("    var response = await ").Append(httpMethodCall).AppendLine(";");
        sb.Append(indent).AppendLine("    if (!response.IsSuccessStatusCode)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        var body = await response.Content.ReadAsStringAsync();");
        sb.Append(indent).Append("        throw new ApiException(HttpMethod.").Append(ToHttpMethodEnumName(method.HttpVerb))
          .Append(", url, response.StatusCode, body);").AppendLine();
        sb.Append(indent).AppendLine("    }");
        sb.AppendLine();

        switch (method.ReturnKind)
        {
            case ApiMethodReturnKind.TaskVoid:
                // nothing further to return
                break;
            case ApiMethodReturnKind.TaskOfStream:
                sb.Append(indent).Append("    return await response.Content.ReadAsStreamAsync(").Append(ctParam?.Name ?? "").AppendLine(");");
                break;
            default:
                sb.Append(indent).Append("    return (await response.Content.ReadFromJsonAsync<")
                  .Append(method.UnwrappedReturnTypeDisplayString).Append(">(cancellationToken: ")
                  .Append(ctParam?.Name ?? "default").AppendLine("))!;");
                break;
        }

        sb.Append(indent).AppendLine("}");
        sb.AppendLine();
    }

    private static string ToHttpMethodEnumName(string verb) => verb switch
    {
        "GET" => "Get",
        "POST" => "Post",
        "PUT" => "Put",
        "DELETE" => "Delete",
        "PATCH" => "Patch",
        _ => "Get",
    };

    private static string BuildRouteInterpolatedString(ApiMethodModel method)
    {
        var template = method.ResolvedRouteTemplate;
        var tokens = RouteTemplate.ParseTokens(template);
        if (tokens.Count == 0)
        {
            return "\"" + template + "\"";
        }

        var routeParamsByToken = method.Parameters
            .Where(p => p.Kind == ParameterKind.Route)
            .ToDictionary(p => p.RouteTokenName!, p => p);

        var sb = new StringBuilder("$\"");
        var i = 0;
        while (i < template.Length)
        {
            if (template[i] == '{')
            {
                var close = template.IndexOf('}', i + 1);
                var inner = template.Substring(i + 1, close - i - 1);
                var name = inner.Split(':')[0].TrimEnd('?');
                if (routeParamsByToken.TryGetValue(name, out var param))
                {
                    sb.Append('{').Append(param.Name).Append('}');
                }

                i = close + 1;
            }
            else
            {
                sb.Append(template[i]);
                i++;
            }
        }

        sb.Append('"');
        return sb.ToString();
    }

    private static string FormatParameter(ApiParameterModel p)
    {
        var suffix = p.HasDefaultValue
            ? $" = {p.DefaultValueLiteral ?? "default"}"
            : p.Kind == ParameterKind.CancellationToken ? " = default" : "";
        return $"{p.TypeDisplayString} {p.Name}{suffix}";
    }
}
