using System.Linq;
using System.Text;
using RouteGen.Generators.Model;

namespace RouteGen.Generators.Emission;

internal static class ControllerEmitter
{
    public static string Generate(ApiInterfaceModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by RouteGen — do not edit. Regenerated on every build. />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.AspNetCore.Authorization;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        var indent = hasNamespace ? "    " : "";
        var baseName = DeriveControllerBaseName(model.InterfaceName);

        sb.Append(indent).Append("[Route(\"").Append(model.BaseRouteTemplate).AppendLine("\")]");
        sb.Append(indent).AppendLine("[ApiController]");
        sb.Append(indent).Append("public abstract class ").Append(baseName).AppendLine(" : ControllerBase");
        sb.Append(indent).AppendLine("{");

        foreach (var method in model.Methods)
        {
            EmitMethod(sb, indent + "    ", method);
        }

        sb.Append(indent).AppendLine("}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void EmitMethod(StringBuilder sb, string indent, ApiMethodModel method)
    {
        var httpAttr = method.HttpVerb switch
        {
            "GET" => "HttpGet",
            "POST" => "HttpPost",
            "PUT" => "HttpPut",
            "DELETE" => "HttpDelete",
            "PATCH" => "HttpPatch",
            _ => "HttpGet",
        };

        sb.Append(indent).Append('[').Append(httpAttr);
        if (!string.IsNullOrEmpty(method.RouteTemplateSuffix))
        {
            sb.Append("(\"").Append(method.RouteTemplateSuffix).Append("\")");
        }

        sb.AppendLine("]");

        foreach (var auth in method.AuthorizationAttributes)
        {
            sb.Append(indent).Append('[').Append(TrimAttributeSuffix(auth.AttributeTypeName));
            var args = auth.ConstructorArgumentLiterals
                .Concat(auth.NamedArguments.Select(na => $"{na.Name} = {na.ValueLiteral}"))
                .ToArray();
            if (args.Length > 0)
            {
                sb.Append('(').Append(string.Join(", ", args)).Append(')');
            }

            sb.AppendLine("]");
        }

        var returnType = method.ReturnKind switch
        {
            ApiMethodReturnKind.TaskVoid => "Task<IActionResult>",
            ApiMethodReturnKind.TaskOfStream => "Task<ActionResult>",
            _ => $"Task<ActionResult<{method.UnwrappedReturnTypeDisplayString}>>",
        };

        sb.Append(indent).Append("public abstract ").Append(returnType).Append(' ').Append(method.Name).Append('(');

        sb.Append(string.Join(", ", method.Parameters.Select(FormatParameter)));
        sb.AppendLine(");");
        sb.AppendLine();
    }

    private static string FormatParameter(ApiParameterModel p)
    {
        var binding = p.Kind switch
        {
            ParameterKind.Route => "[FromRoute] ",
            ParameterKind.Query => "[FromQuery] ",
            ParameterKind.Body => "[FromBody] ",
            ParameterKind.CancellationToken => "",
            _ => "",
        };

        var suffix = p.HasDefaultValue ? $" = {p.DefaultValueLiteral}" : (p.Kind == ParameterKind.CancellationToken ? " = default" : "");
        return $"{binding}{p.TypeDisplayString} {p.Name}{suffix}";
    }

    private static string TrimAttributeSuffix(string name) =>
        name.EndsWith("Attribute") ? name.Substring(0, name.Length - "Attribute".Length) : name;

    internal static string DeriveControllerBaseName(string interfaceName)
    {
        var trimmed = interfaceName.StartsWith("I") && interfaceName.Length > 1 && char.IsUpper(interfaceName[1])
            ? interfaceName.Substring(1)
            : interfaceName;
        return trimmed + "ControllerBase";
    }
}
