<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RouteGen.Abstractions\RouteGen.Abstractions.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="8.0.8" />
    <PackageReference Include="RouteGen.Abstractions" Version="0.1.0" />
  </ItemGroup>

</Project>
